//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawprint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowList
    {
        public string UserID { get; set; }
        public int PetID { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
